require_relative 'resources/s3_bucket_resource'
require_relative 'resources/vpc_resource'
require_relative 'resources/subnets_resource'
require_relative 'resources/vpn_gateway_resource'
require_relative 'resources/ec2_instance_resource'
require_relative 'resources/dynamodb_resource'
require_relative 'resources/sqs_queue_resource'
require_relative 'resources/sns_resource'
require_relative 'resources/swf_resource'
require_relative 'resources/launch_configuration_resource'
require_relative 'resources/auto_scaling_group_resource'
require_relative 'resources/elb_resource'
require_relative 'resources/iam_role_resource'

